// Authentication
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// UI
export const TOGGLE_SNACKBAR = 'TOGGLE_SNACKBAR';

// Modules
export const REQUEST_MODULES = 'REQUEST_MODULES';
export const REQUEST_MODULES_SUCCESS = 'REQUEST_MODULES_SUCCESS';
export const REQUEST_MODULES_FAIL = 'REQUEST_MODULES_FAIL';

// Courses
export const REQUEST_COURSES = 'REQUEST_COURSES';
export const REQUEST_COURSES_SUCCESS = 'REQUEST_COURSES_SUCCESS';
export const REQUEST_COURSES_FAIL = 'REQUEST_COURSES_FAIL';

// Comments
export const REQUEST_FEEDBACKS = 'REQUEST_FEEDBACKS';
export const REQUEST_FEEDBACKS_SUCCESS = 'REQUEST_FEEDBACKS_SUCCESS';
export const REQUEST_FEEDBACKS_FAIL = 'REQUEST_FEEDBACKS_FAIL';

export const SUBMIT_FEEDBACK = 'SUBMIT_FEEDBACK';
export const SUBMIT_FEEDBACK_SUCCESS = 'SUBMIT_FEEDBACK_SUCCESS';
export const SUBMIT_FEEDBACK_FAIL = 'SUBMIT_FEEDBACK_FAIL';

export const SELECT_ACTIVE_COURSE = 'SELECT_ACTIVE_COURSE';
export const SELECT_ACTIVE_FAIL = 'SELECT_ACTIVE_COURSE_FAIL';
