export default [
  { 'id': 'DIGIT', 'name': 'Yleistä kursseista', 'credits': 0 },
  { 'id': 'MATE5398', 'name': 'Insinöörimatematiikka A', 'credits': 5 },
  { 'id': 'MATE5399', 'name': 'Insinöörimatematiikka B', 'credits': 4 },
  { 'id': 'MATE5400', 'name': 'Insinöörimatematiikka C', 'credits': 5 },
  { 'id': 'MATE5401', 'name': 'Insinöörimatematiikka D', 'credits': 5 },
  { 'id': 'FFYS5004', 'name': 'Fysiikan peruskurssi 2', 'credits': 4 },
  { 'id': 'FFYS5003', 'name': 'Fysiikan peruskurssi 1', 'credits': 4 },
  { 'id': 'FFYS5005', 'name': 'Fysiikan peruskurssi 3', 'credits': 4 },
  { 'id': 'FFYS5006', 'name': 'Fysiikan peruskurssi 4', 'credits': 4 },
  { 'id': 'TILM3568', 'name': 'Todennäköisyyslaskenta sivuaineopiskelijoille', 'credits': 4 },
  { 'id': 'MATE5353', 'name': 'Johdatus automaattien teoriaan', 'credits': 4 },
  { 'id': 'DTEK1045', 'name': 'Insinöörityön perusteet', 'credits': 5 },
  { 'id': 'DTEK1043', 'name': 'Opiskelun ja työelämän tietotekniikka', 'credits': 4 },
  { 'id': 'TKO_2038', 'name': 'Algoritmien ja ohjelmoinnin peruskurssi', 'credits': 6 },
  { 'id': 'BKEM5110', 'name': 'Biotekniikka 1', 'credits': 2 },
  { 'id': 'EKEH1177', 'name': 'Elintarvikekehityksen perusteet', 'credits': 2 },
  { 'id': 'DIBT0060', 'name': 'Bioteekkarin avaimet opiskeluun ja työelämään', 'credits': 2 },
  { 'id': 'DIBT0201', 'name': 'Julkaisukäytännöt', 'credits': 1 },
  { 'id': 'TKO_5736', 'name': 'Tietojenkäsittelyn perusteet I', 'credits': 5 },
  { 'id': 'KEMI6301', 'name': 'Kemian peruskurssi I', 'credits': 4 },
  { 'id': 'KEMI6302', 'name': 'Kemian peruskurssi II', 'credits': 4 },
  { 'id': 'KEMI6303', 'name': 'Kemian työmenetelmät I', 'credits': 4 },
  { 'id': 'KEMI6304', 'name': 'Kemian työmenetelmät II', 'credits': 5 },
  { 'id': 'KEMI6103', 'name': 'Kemia III', 'credits': 4 },
  { 'id': 'KEMI6104', 'name': 'Kemia IV', 'credits': 4 },
  { 'id': 'BKEM5030', 'name': 'Solu ja biomolekyylit - teoria', 'credits': 6 },
  { 'id': 'BKEM5031', 'name': 'Solu ja biomolekyylit - käytäntö', 'credits': 4 },
  { 'id': 'BKEM5020', 'name': 'Molekyylibiologia - teoria', 'credits': 4 },
  { 'id': 'BKEM5021', 'name': 'Molekyylibiologia - käytäntö', 'credits': 6 },
  { 'id': 'ETT_1004', 'name': 'Mikroprosessorit', 'credits': 5 },
  { 'id': 'DTEK1066', 'name': 'Hajautetut ohjelmistojärjestelmät ja pilvipalvelut', 'credits': 5 },
  { 'id': 'TKO_3107', 'name': 'Tietorakenteet ja algoritmit', 'credits': 5 },
  { 'id': 'DTEK1046', 'name': 'Ohjelmointikielet ja -paradigmat', 'credits': 5 },
  { 'id': 'ETT_2067', 'name': 'Lineaariset järjestelmät ja piirit', 'credits': 5 },
  { 'id': 'TKO_3122', 'name': 'Tietokantojen perusteet 1', 'credits': 5 },
  { 'id': 'BKEM5010', 'name': 'Mikrobiologia - teoria', 'credits': 4 },
  { 'id': 'BKEM5011', 'name': 'Mikrobiologia - käytäntö', 'credits': 3 },
  { 'id': 'BKEM5151', 'name': 'Proteiinit ja entsyymit', 'credits': 10 },
  { 'id': 'BKEM5111', 'name': 'Biotekniikka 2', 'credits': 3 },
  { 'id': 'BKEM5112', 'name': 'Biotekniikka 3', 'credits': 2 },
  { 'id': 'DIBT0061', 'name': 'Immunomäärityksen kehittäminen', 'credits': 4 },
  { 'id': 'DIBT0062', 'name': 'Biotekniset järjestelmät', 'credits': 4 },
  { 'id': 'DIBT0058', 'name': 'Puhdastilatyöskentely', 'credits': 2 },
  { 'id': 'EKEH1176', 'name': 'Kromatografinen analytiikka bioaloilla', 'credits': 3 },
  { 'id': 'EKEH1179', 'name': 'Elintarvikkeiden laatutekijät', 'credits': 2 },
  { 'id': 'EKEH1178', 'name': 'Elintarviketeknologia', 'credits': 3 },
  { 'id': 'DTEK1201', 'name': 'Ohjelmistotuotannon peruskurssi', 'credits': 4 },
  { 'id': 'DTEK1048', 'name': 'Olio-ohjelmoinnin metodiikka', 'credits': 4 },
  { 'id': 'DTEK1049', 'name': 'Käyttöliittymät', 'credits': 4 },
  { 'id': 'DTEK1051', 'name': 'Tietokonearkkitehtuurit ja käyttöjärjestelmät', 'credits': 4 },
  { 'id': 'DTEK1019', 'name': 'Sulautetut prosessorijärjestelmät', 'credits': 4 },
  { 'id': 'ETT_2068', 'name': 'Elektroniikkajärjestelmät', 'credits': 4 },
  { 'id': 'DTEK1050', 'name': 'Tietoverkkotekniikat', 'credits': 4 },
  { 'id': 'ETT_3005', 'name': 'Digitaaliset tietoliikennejärjestelmät', 'credits': 5 },
  { 'id': 'ETT_2026', 'name': 'Digitaalinen signaalinkäsittely', 'credits': 3 },
  { 'id': 'DTEK1061', 'name': 'Tietotekniikan laboratorioprojekti', 'credits': 4 },
  { 'id': 'DIBT0004', 'name': 'TkK-tutkielma ja seminaari', 'credits': 8 },
  { 'id': 'DTEK2000', 'name': 'TkK-tutkielma', 'credits': 8 },
  { 'id': 'KIRU2322', 'name': 'Ruotsin kieli: Matemaattis-luonnontieteellinen tiedekunta. Kirjallinen', 'credits': 2 },
  { 'id': 'KIRU2342', 'name': 'Ruotsin kieli: Matemaattis-luonnontieteellinen tiedekunta. Suullinen', 'credits': 2 },
  { 'id': 'KIEN2367', 'name': 'Englannin kieli: Technical Writing', 'credits': 2 },
  { 'id': 'KIEN2366', 'name': 'Englannin kieli: Technical English', 'credits': 2 },
  { 'id': 'KISU3322', 'name': 'Suomen kieli: Matemaattis-luonnontiet. Kirajllinen työ', 'credits': 1 },
  { 'id': 'KISU3323', 'name': 'Insinööritieteiden kirjallinen viestintä', 'credits': 1 },
  { 'id': 'KIPV3333', 'name': 'Puheviestintä', 'credits': 2 },
  { 'id': 'TILM3553', 'name': 'Todennäköisyyslaskennan peruskurssi', 'credits': 4 },
  { 'id': 'TILM3556', 'name': 'Aineiston hankinta ja tutkimusasetelmat', 'credits': 5 },
  { 'id': 'TILM3558', 'name': 'Harjoitustyö', 'credits': 3 },
  { 'id': 'TILM3525', 'name': 'Tilastotieteen peruskurssi soveltajille', 'credits': 8 },
  { 'id': 'TILM3557', 'name': 'Tilastollisten mallien peruskurssi', 'credits': 6 },
  { 'id': 'BIOL4060', 'name': 'Bioetiikka', 'credits': 2 },
  { 'id': 'BIOL4051', 'name': 'Biologinen aineisto: johdatus tilastomenetelmiin', 'credits': 4 },
  { 'id': 'BIOL1201', 'name': 'Eläinfysiologian perusteet', 'credits': 3 },
  { 'id': 'BIOL1301', 'name': 'Genetiikan perusteet', 'credits': 3 },
  { 'id': 'BKEM5160', 'name': 'Solu ja energia - teoria', 'credits': 6 },
  { 'id': 'BKEM5161', 'name': 'Solu ja energia - käytäntö', 'credits': 4 },
  { 'id': 'BKEM5140', 'name': 'Molekulaarinen kasvibiologia - teoria', 'credits': 6 },
  { 'id': 'BKEM5120', 'name': 'Immunologia - teoria', 'credits': 4 },
  { 'id': 'KEMI6107', 'name': 'Analyyttinen kemia', 'credits': 6 },
  { 'id': 'KEMI6108', 'name': 'Epäorgaaninen kemia', 'credits': 5 },
  { 'id': 'KEMI6110', 'name': 'Orgaaninen kemia', 'credits': 7 },
  { 'id': 'KEMI6109', 'name': 'Fysikaalinen kemia I', 'credits': 5 },
  { 'id': 'KEMI6115', 'name': 'Fysikaalinen kemia II', 'credits': 5 },
  { 'id': 'KEMI6116', 'name': 'Kemiallinen biologia', 'credits': 4 },
  { 'id': 'KEMI6121', 'name': 'Spektroskopian perusteet', 'credits': 4 },
  { 'id': 'KEMI6119', 'name': 'Materiaalikemia ja nanoteknologia', 'credits': 4 },
  { 'id': 'KEMI6117', 'name': 'Laskennallinen kemia ja molekyylimallinnus', 'credits': 4 },
  { 'id': 'KEMI6120', 'name': 'Siirtymämetallien bioepäorgaaninen kemia', 'credits': 4 },
  { 'id': 'DTEK1064', 'name': 'Tietoyhteiskunta ja kyberturvallisuus', 'credits': 4 },
  { 'id': 'DTEK1039', 'name': 'Tiedonsiirron perusteet', 'credits': 5 },
  { 'id': 'TKO_2005', 'name': 'Olio-ohjelmoinnin perusteet', 'credits': 5 },
  { 'id': 'ETT_2066', 'name': 'Elektroniset laitteistot ja kestävä kehitys', 'credits': 5 },
  { 'id': 'MATE5356', 'name': 'Vektorilaskenta', 'credits': 4 },
  { 'id': 'SMAT5176', 'name': 'Numeerinen analyysi', 'credits': 4 },
  { 'id': 'MATE5354', 'name': 'Lebesguen mitta ja integraali', 'credits': 9 },
  { 'id': 'SMAT5108', 'name': 'Matemaattinen optimointi I', 'credits': 4 },
  { 'id': 'SMAT5109', 'name': 'Matemaattinen optimointi II', 'credits': 4 },
  { 'id': 'SMAT5045', 'name': 'Differentiaaliyhtälöt', 'credits': 5 },
  { 'id': 'MATE5355', 'name': 'Tieteellinen laskenta', 'credits': 4 },
  { 'id': 'MATE5060', 'name': 'Algebran peruskurssi I', 'credits': 5 },
  { 'id': 'MATE5061', 'name': 'Algebran peruskurssi II', 'credits': 4 },
  { 'id': 'MATE5074', 'name': 'Algoritminen matematiikka', 'credits': 4 },
  { 'id': 'MATE5039', 'name': 'Kombinatoriikka', 'credits': 4 },
  { 'id': 'MATE5114', 'name': 'Logiikka', 'credits': 4 },
  { 'id': 'MATE5123', 'name': 'Lukuteoria', 'credits': 4 },
];
